version: '3.5'

services:
  bindwebmin:
    build: .
    restart: always
    volumes:
      - ./data:/data
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 10000:10000
    environment:
      - ROOT_PASSWORD=password
      - WEBMIN_ENABLED=true
